name = "Weapons-Balance-CSLA"
prefix = "wb_csla"
mainprefix = "z"

[properties]
author = "johnb43"
url = "https://github.com/johnb432"

[files]
include = [
    "CHANGELOG.md",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
